### ISSUE TITLE
[Fix] 전체 코드 검토

### ISSUE THREAD

**Issue by ChooSeoyeon** [TeamRecorDream/RecorDream-Server#65]
## 🦾  Fix Description
전체 코드 검토

## 📝  To-do
- [x] User  관련 코드 검토 및 수정
- [x] Record 관련 코드 검토 및 수정
- [x] Voice 관련 코드 검토 및 수정
- [x] 주석 지우기
