### ISSUE TITLE
[Fix] Record model에 color, genre 수정

### ISSUE THREAD

**Issue by ChooSeoyeon** [TeamRecorDream/RecorDream-Server#73]
## 🦾  Fix Description
Record에 color, genre 수정

## 📝  To-do
- [x] genre default값 넣어주기
- [x] color, emotion, genre 범위 밖 에러 처리
- [x] emotion default값 변경
