### ISSUE TITLE
[Test] 시연 test 코드 작성

### ISSUE THREAD

**Issue by ksiyeon27** [TeamRecorDream/RecorDream-Server#83]
## 📌  Feature Description
내가 짠 api 의 테스트 코드 작성

## 📝  To-do
- [ ] POST /voice
- [ ] GET /voice/:voiceId
- [ ] PATCH /record/:recordId
- [ ] GET  /record/:recordId
- [ ] DELETE  /record/:recordId
